[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  zinggjm/GxEPD2
  adafruit/Adafruit GFX Library
  adafruit/Adafruit BusIO
  olikraus/U8g2_for_Adafruit_GFX

build_flags =
  -D CORE_DEBUG_LEVEL=3
