#!/usr/bin/env python3
"""
Icon bitmap generator for the AI Mobile E-Ink Reader.

Converts PNG/BMP images in assets/icons/ into 1-bpp C header files
that can be embedded into the firmware.

Usage:
    python3 tools/generate_icons.py              # use default 64x64 size
    python3 tools/generate_icons.py --size 128   # override icon size

File naming convention (maps to ui_icon_kind_t):
    reader.png   → UI_ICON_READER (index 0)
    weather.png  → UI_ICON_WEATHER (index 1)
    calendar.png → UI_ICON_CALENDAR (index 2)
    english.png  → UI_ICON_ENGLISH (index 3)
    settings.png → UI_ICON_SETTINGS (index 4)
    about.png    → UI_ICON_ABOUT (index 5)
"""

import argparse
import sys
from pathlib import Path

from PIL import Image

ICON_NAMES = [
    "reader",
    "weather",
    "calendar",
    "english",
    "settings",
    "about",
    # Weather condition icons
    "weather_sunny",
    "weather_cloudy",
    "weather_rainy",
    "weather_snowy",
]

ICON_DIR = Path("assets/icons")
DEFAULT_SIZE = 52


def load_and_convert(path: Path, target_size: int) -> list[list[int]]:
    """Load an image file, convert to 1-bpp bitmap (list of rows, each row is a list of 0/1).

    Returns a target_size x target_size grid where 1 = black pixel, 0 = white/transparent.
    """
    img = Image.open(path).convert("RGBA")

    # Resize to target size using LANCZOS for quality
    img = img.resize((target_size, target_size), Image.LANCZOS)

    pixels = img.load()
    bitmap: list[list[int]] = []

    for y in range(target_size):
        row: list[int] = []
        for x in range(target_size):
            r, g, b, a = pixels[x, y]
            # A pixel is "black" if it's opaque (alpha > 128) AND dark (luminance <= 128)
            # Transparent pixels are treated as white (background)
            if a > 128:
                luminance = 0.299 * r + 0.587 * g + 0.114 * b
                row.append(1 if luminance <= 128 else 0)
            else:
                row.append(0)
        bitmap.append(row)

    return bitmap


def bitmap_to_bytes(bitmap: list[list[int]], size: int) -> list[int]:
    """Pack a 2D bitmap into 1-bpp bytes (MSB first within each byte)."""
    bytes_per_row = (size + 7) // 8
    data: list[int] = []
    for row in bitmap:
        for byte_idx in range(bytes_per_row):
            value = 0
            for bit in range(8):
                col = byte_idx * 8 + bit
                if col < size and row[col]:
                    value |= 1 << (7 - bit)
            data.append(value)
    return data


def generate_header(bitmap_map: dict[str, list[int]], size: int, out_path: Path) -> None:
    """Generate a C header file with the icon bitmap data."""
    bytes_per_row = (size + 7) // 8
    total_bytes = bytes_per_row * size

    lines: list[str] = []
    lines.append("/* Auto-generated by tools/generate_icons.py — DO NOT EDIT */")
    lines.append("#ifndef ICONS_BITMAP_H")
    lines.append("#define ICONS_BITMAP_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define ICON_BITMAP_SIZE {size}")
    lines.append(f"#define ICON_BITMAP_BYTES_PER_ROW {bytes_per_row}")
    lines.append(f"#define ICON_BITMAP_TOTAL_BYTES {total_bytes}")
    lines.append("")
    lines.append(f"/* Number of icons with bitmap data available */")
    lines.append(f"#define ICON_BITMAP_COUNT {len(bitmap_map)}")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    uint8_t bitmap[" + str(total_bytes) + "];")
    lines.append("} icon_bitmap_t;")
    lines.append("")
    lines.append("/*")
    lines.append(" * Indexed by ui_icon_kind_t enum value.")
    lines.append(" * Entries are present only for icons that have a corresponding image file.")
    lines.append(" * Check index < ICON_BITMAP_COUNT before accessing.")
    lines.append(" */")
    lines.append("static const icon_bitmap_t icon_bitmaps[] = {")

    for name in ICON_NAMES:
        if name in bitmap_map:
            data = bitmap_map[name]
            hex_bytes = ", ".join(f"0x{b:02x}" for b in data)
            lines.append(f"    /* {name} */")
            lines.append(f"    {{{{{hex_bytes}}}}},")
        else:
            lines.append(f"    /* {name} — no bitmap, using procedural fallback */")
            lines.append(f"    {{{{0}}}},  /* placeholder */")

    lines.append("};")
    lines.append("")
    lines.append("/*")
    lines.append(" * Returns 1 if the given icon kind has a real bitmap,")
    lines.append(" * 0 if the caller should fall back to procedural drawing.")
    lines.append(" */")
    lines.append("#define ICON_HAS_BITMAP(kind) \\")
    lines.append("    ((unsigned)(kind) < ICON_BITMAP_COUNT)")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {out_path} with {len(bitmap_map)} icon bitmap(s), size={size}x{size}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate icon bitmaps from PNG/BMP images")
    parser.add_argument("--size", type=int, default=DEFAULT_SIZE, help=f"Icon size in pixels (default: {DEFAULT_SIZE})")
    args = parser.parse_args()

    size = args.size
    if size < 1 or size > 512:
        print(f"Error: icon size must be between 1 and 512, got {size}", file=sys.stderr)
        sys.exit(1)

    if not ICON_DIR.is_dir():
        ICON_DIR.mkdir(parents=True, exist_ok=True)
        print(f"Created {ICON_DIR}/ — place PNG/BMP icon images there and re-run this script.")
        print(f"Expected files: {', '.join(n + '.png' for n in ICON_NAMES)}")
        # Generate an empty placeholder header so the project still compiles
        generate_header({}, size, ICON_DIR / "icons_bitmap.h")
        return

    # Scan for image files matching known icon names
    image_map: dict[str, Path] = {}
    for name in ICON_NAMES:
        for ext in ("png", "bmp", "gif", "jpg", "jpeg"):
            candidate = ICON_DIR / f"{name}.{ext}"
            if candidate.is_file():
                image_map[name] = candidate
                break

    if not image_map:
        print(f"No icon images found in {ICON_DIR}/")
        print(f"Expected files: {', '.join(n + '.png' for n in ICON_NAMES)}")
        generate_header({}, size, ICON_DIR / "icons_bitmap.h")
        return

    # Convert images to bitmaps
    bitmap_map: dict[str, list[int]] = {}
    for name, path in sorted(image_map.items()):
        print(f"  Converting {path.name} ({size}x{size})...")
        bitmap = load_and_convert(path, size)
        bitmap_map[name] = bitmap_to_bytes(bitmap, size)

    generate_header(bitmap_map, size, ICON_DIR / "icons_bitmap.h")


if __name__ == "__main__":
    main()
