idf_component_register(
    SRCS
        "main_esp.c"
        "gfx/gfx.c"
        "app/app_state.c"
        "app/app_page_names.c"
        "app/app_persistence.c"
        "app/file_browser.c"
        "app/reader_library.c"
        "app/reader_library_path.c"
        "app/epub_reader.c"
        "ui/pages.c"
        "ui/page_simple.c"
        "ui/page_layout.c"
        "ui/icons.c"
        "font/font.c"
        "font/font_metadata.c"
        "platform/epd_frame.c"
        "platform/ssd1677.c"
        "platform/input_debounce.c"
        "platform/storage_io.c"
        "platform/esp_display.c"
        "platform/esp_async_runtime.c"
        "platform/esp_input.c"
        "platform/esp_sd.c"
        "platform/esp_time_sync.c"
        "platform/esp_weather.c"
        "platform/esp_battery.c"
        "platform/esp_power.c"
        "platform/esp_config_backup.c"
        "platform/esp_web_admin.c"
        "web/admin_html.S"
    INCLUDE_DIRS
        "."
        "../assets"
    REQUIRES
        esp_driver_gpio
        esp_driver_spi
        fatfs
        freertos
        esp_event
        esp_netif
        esp_rom
        esp_wifi
        esp_http_server
        esp_http_client
        esp_adc
        esp_pm
        mbedtls
        log
        lwip
        nvs_flash
)
